baseurl = "https://www.example.com/"
languageCode = "en-us"
title = "Blackburn Theme Demo"
author = "Yoshiharu Yamashita"
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10
DefaultContentLanguage = "en"
[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "A Hugo Theme"
  brand = "Blackburn"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

  [languages.en]
      weight = 10
      languageName = "English"
      languageCode = "en-us"
      description = "Scriptor is a minimal Hugo blogging theme for writers."
      message = "John Doe is a designer, speaker, and author. He is the Creative Director of Awesome Design studio, co-founder of magazine Camera and a coffee junkie."
      copyright = "All rights reserved."

      [[languages.en.menu.main]]
        name = "Home"
        pre = "<i class='fa fa-home fa-fw'></i>"
        weight = 1
        identifier = "home"
        url = "/"
      [[languages.en.menu.main]]
          name = "About"
          pre = "<i class='fa fa-user fa-fw'></i>"
          weight = 2
          identifier = "about"
          url = "/about/"

  [languages.gu]
      weight = 20
      languageName = "Gujarati"
      languageCode = "de-de"
      description = "Scriptor ist ein minimalistisches Hugo-Theme für Blogger."
      message = "John Doe ist Designer, Referent und Autor. Er ist der Creative Director bei Awesome Design Studio, Mitbegründer des Magazines Camera und ein Kaffee-Junkie."
      copyright = "Alle Rechte vorbehalten."
      paginatePath = "seite"

      [[languages.gu.menu.main]]
        name = "ઘર"
        pre = "<i class='fa fa-home fa-fw'></i>"
        weight = 1
        identifier = "home"
        url = "/"
      [[languages.gu.menu.main]]
          name = "અમારા વિશે"
          pre = "<i class='fa fa-user fa-fw'></i>"
          weight = 2
          identifier = "about"
          url = "/about/"
   [languages.hi]
      weight = 30
      languageName = "Hindi"
      languageCode = "de-de"
      description = "Scriptor ist ein minimalistisches Hugo-Theme für Blogger."
      message = "John Doe ist Designer, Referent und Autor. Er ist der Creative Director bei Awesome Design Studio, Mitbegründer des Magazines Camera und ein Kaffee-Junkie."
      copyright = "Alle Rechte vorbehalten."
      paginatePath = "seite"

      [[languages.hi.menu.main]]
        name = "घर"
        pre = "<i class='fa fa-home fa-fw'></i>"
        weight = 1
        identifier = "home"
        url = "/"
      [[languages.hi.menu.main]]
        name = "हमारे बारे में"
        pre = "<i class='fa fa-user fa-fw'></i>"
        weight = 2
        identifier = "about"
        url = "/about/"
# [social]
#   # Link your social networking accouns to the side menu
#   # by entering your username or ID.
#   twitter = "*"
#   facebook = "*"
#   instagram = "*"
#   github = "yoshiharuyamashita"
#   stackoverflow = "*"
#   linkedin = "*"
